"""Copy canonical documents into the MkDocs tree.

Several pages have their home elsewhere in the repository: the agent skill is
loaded by Claude from `skills/`, and CONTRIBUTING, ROADMAP and LICENSE-DATA
are read on GitHub. Rather than maintaining a second copy, those files are
copied into `docs/` at build time and the copies are gitignored, so there is
exactly one source of truth for each.

Run before `mkdocs build` or `mkdocs serve`:

    make docs
    python scripts/sync_docs.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"

# source in the repository -> destination inside docs/
SYNC = {
    "skills/ghana-geosql/SKILL.md":                    "skill/index.md",
    "skills/ghana-geosql/references/postgis.md":       "skill/postgis.md",
    "skills/ghana-geosql/references/duckdb.md":        "skill/duckdb.md",
    "skills/ghana-geosql/references/data-catalog.md":  "skill/data-catalog.md",
    "skills/ghana-geosql/references/crs.md":           "skill/crs.md",
    "skills/ghana-geosql/references/map-styling.md":   "skill/map-styling.md",
    "CONTRIBUTING.md":                                 "project/contributing.md",
    "AGENTS.md":                                       "project/agents.md",
    "ROADMAP.md":                                      "project/roadmap.md",
    "LICENSE-DATA.md":                                 "project/licensing.md",
}

# Links that point at repository paths need rewriting for the site.
LINK_FIXES = [
    (r"\]\(references/([a-z-]+)\.md\)",                  r"](\1.md)"),
    (r"\]\(skills/ghana-geosql/references/([a-z-]+)\.md\)", r"](../skill/\1.md)"),
    (r"\]\(docs/([a-z-]+)\.md\)",                        r"](../\1.md)"),
    (r"\]\(AGENTS\.md\)",                                r"](agents.md)"),
    (r"\]\(CONTRIBUTING\.md\)",                          r"](contributing.md)"),
    (r"\]\(ROADMAP\.md\)",                               r"](roadmap.md)"),
    (r"\]\(LICENSE-DATA\.md\)",                          r"](licensing.md)"),
    (r"\]\(LICENSE\)",
     r"](https://github.com/YOUR-ORG/ghana-geostack/blob/main/LICENSE)"),
    (r"\]\(config/([a-z]+)\.yml\)",
     r"](https://github.com/YOUR-ORG/ghana-geostack/blob/main/config/\1.yml)"),
    (r"\]\(evals/evals\.json\)",
     r"](https://github.com/YOUR-ORG/ghana-geostack/blob/main/evals/evals.json)"),
    (r"\]\(data/reference/\)",
     r"](https://github.com/YOUR-ORG/ghana-geostack/tree/main/data/reference)"),
]

BANNER = (
    "<!-- Generated by scripts/sync_docs.py from {source}. "
    "Edit that file, not this one. -->\n\n"
)


def strip_front_matter(text: str) -> tuple[str, dict]:
    """Pull YAML front matter out of a skill file and return it separately."""
    if not text.startswith("---\n"):
        return text, {}
    end = text.find("\n---\n", 4)
    if end == -1:
        return text, {}
    block = text[4:end]
    meta = {}
    for line in block.splitlines():
        if ":" in line and not line.startswith(" "):
            key, _, value = line.partition(":")
            meta[key.strip()] = value.strip()
    return text[end + 5:].lstrip("\n"), meta


def sync() -> int:
    written = 0
    for source, destination in SYNC.items():
        source_path = ROOT / source
        if not source_path.exists():
            print(f"  missing {source}")
            continue

        text = source_path.read_text(encoding="utf-8")
        text, meta = strip_front_matter(text)

        for pattern, replacement in LINK_FIXES:
            text = re.sub(pattern, replacement, text)

        # A skill file's description becomes the page summary.
        if meta.get("description"):
            first_heading = text.find("\n", text.find("# "))
            text = (text[:first_heading + 1]
                    + f"\n!!! abstract \"What this does\"\n\n    {meta['description']}\n"
                    + text[first_heading + 1:])

        target = DOCS / destination
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(BANNER.format(source=source) + text, encoding="utf-8")
        written += 1
        print(f"  {source} -> docs/{destination}")

    return written


if __name__ == "__main__":
    print("Syncing documentation")
    count = sync()
    print(f"\n{count} pages synced")
